// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * Remember to use the same float bit size in the result, which was used to create number values
 * when creating `NewToken()`
 * @returns {Promise<number> & { cancel(): void }}
 */
export function Evaluate() {
    let $resultPromise = /** @type {any} */($Call.ByID(1904246335));
    return $resultPromise;
}

/**
 * Insert a token into the expression tree
 * @param {string} $in
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Insert($in) {
    let $resultPromise = /** @type {any} */($Call.ByID(2800577289, $in));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Reset() {
    let $resultPromise = /** @type {any} */($Call.ByID(3841943515));
    return $resultPromise;
}
